### ISSUE TITLE
Different filenames same theme

### ISSUE THREAD

**Issue by mssdvd** [DaveDavenport/rofi-themes#10]

**Comment by carnager** [comment]
You somehow forgot to describe your problem...

**Comment by mssdvd** [comment]
I'm sorry. All the rasi files inside Themes dir have the same content.

![image](https://user-images.githubusercontent.com/18464329/31775204-3f38f854-b4e8-11e7-97fd-7e2db55dc304.png)

**Comment by carnager** [comment]
ah right

**Comment by mssdvd** [comment]
Arc-Dark-alternate and Arc-Dark haven't a rasi replacement.

**Comment by DaveDavenport** [comment]
The idea behind rofi-themes was to be a staging area for moving into the main branch.
