### ISSUE TITLE
theme.rasi not work

### ISSUE THREAD

**Issue by Wabri** [DaveDavenport/rofi-themes#20]
I put the .rasi themes on ~/.config/rofi/ and in /usr/share/rofi/themes but when i launch rofi-themes-selection it does not see them. And if i execute 'rofi -theme theme-name' nothing append.
Where am I doing wrong?

**Comment by carnager** [comment]
Most likely your rofi version is too old for the new theme format

**Comment by CadaverLab** [comment]
I had to put my themes in ~/.local/share/rofi/themes for them to work

**Comment by carnager** [comment]
which is the correct path, but still the other two should work too

**Comment by Wabri** [comment]
i install with apt-get

**Comment by Wabri** [comment]
Actually in the readme of the rofi repo there is a note "Note that the latest version of rofi in Ubuntu 16.04 is extremely obsolete (v0.15.11)" I think is the same as ubuntu 17.10 so this is the problem.

**Comment by dikiaap** [comment]
Yes. Same as me. I ended up installing rofi via compiling.
