### ISSUE TITLE
Parsing error - argb with only 7 chars as input.

### ISSUE THREAD

**Issue by fwarmuth** [DaveDavenport/rofi-themes#9]
Hey,
i am getting a "Error while parsing theme:" if i use Arc-Dark.theme.
If i change:
`rofi.color-normal:                   argb:0383c4a, #c4cbd4, argb:96404552, #4084d6, #f9f9f9`
`rofi.color-urgent:                   argb:02d303b, #cc6666, argb:e52d303b, #a54242, #f9f9f9`
`rofi.color-active:                   argb:02d303b, #b5bd68, argb:e42d303b, #8c9440, #f9f9f9`

to
`rofi.color-normal:                   argb:0383c4a0, #c4cbd4, argb:96404552, #4084d6, #f9f9f9`
`rofi.color-urgent:                   argb:02d303b0, #cc6666, argb:e52d303b, #a54242, #f9f9f9`
`rofi.color-active:                   argb:02d303b0, #b5bd68, argb:e42d303b, #8c9440, #f9f9f9`

Notice argb:0383c4a**0**

and everything works as expected.
Seems that "argb" needs the full 8byte input.

i am using version `rofi 1.4.2-1`.

Should i open a pullreq?

regards!

btw - nice themes!

**Comment by DaveDavenport** [comment]
See: https://github.com/DaveDavenport/rofi-themes/pull/8
